services:

  db:
    image: postgres:16
    container_name: postgres_db
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgresAdmin
      POSTGRES_PASSWORD: postgresAdmin
      POSTGRES_DB: user-db
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - minha-rede-local-docker

  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres_pgAdmin
    ports:
      - "5050:80"  # Acesse o pgAdmin na URL http://localhost:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - postgresql-server-config:/var/lib/postgresql/data
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - minha-rede-local-docker

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"     # AMQP (apps)
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - minha-rede-local-docker

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"   # Porta SMTP
      - "8025:8025"   # Interface web
    networks:
      - minha-rede-local-docker

networks:
  minha-rede-local-docker:
    external: true

volumes:
  postgresql-data:
  postgresql-server-config:
  rabbitmq_data:



# commands
  # network-ls: docker network ls
  # network   : docker network create minha-rede-local-docker
  # build     : docker-compose -p minha-infra -f docker-compose.infra.yml build
  # start     : docker-compose -p minha-infra -f docker-compose.infra.yml up -d
  # recreate  : docker-compose -p minha-infra -f docker-compose.infra.yml up -d --force-recreate


#dotnet ef migrations add InitialCreate
#dotnet ef database update